services:
  shop-auth:
    restart: always
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    container_name: shop-auth
    ports:
      - "8001:8000"
    command: uvicorn main:app --host=0.0.0.0 --port=8000
