services:
  shop-gateway:
    restart: always
    build:
      context: src/gateway
      dockerfile: Dockerfile
    container_name: shop-gateway
    ports:
      - "8000:8000"
    command: uvicorn app:app --host=0.0.0.0 --port=8000 --reload
