"""Initial

Revision ID: 75270062b0cb
Revises: 
Create Date: 2025-04-18 11:33:38.444684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75270062b0cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('steam_id', sa.String(length=17), nullable=False),
    sa.Column('persona_name', sa.String(length=255), nullable=False),
    sa.Column('profile_url', sa.String(length=255), nullable=False),
    sa.Column('avatar_medium', sa.String(length=255), nullable=False),
    sa.Column('avatar_full', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issued_tokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('subject', sa.String(length=17), nullable=False),
    sa.Column('expired', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('access', 'refresh', name='tokentype'), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issued_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
