"""Initial

Revision ID: 6cfae33da497
Revises:
Create Date: 2025-04-11 07:37:10.525793

"""
import sqlalchemy as sa

from collections.abc import Sequence
from alembic         import op
from typing          import Union


# revision identifiers, used by Alembic.
revision: str = '6cfae33da497'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issued_tokens',
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('subject', sa.String(length=17), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issued_tokens')
    # ### end Alembic commands ###
